using AutoMapper;
using SmartInventory.Core.Entities;
using SmartInventory.Services.DTOs;

namespace SmartInventory.Services.Mapping
{
    /// <summary>
    /// AutoMapper profile for mapping between Product entities and DTOs.
    /// </summary>
    public class MappingProfile : Profile
    {
        public MappingProfile()
        {
            // ---------------------------
            // CreateProductDto → Product
            // ---------------------------
            // Used when creating a new product.
            // Id is generated by the database, so we don't map it.
            CreateMap<CreateProductDto, Product>();

            // ---------------------------
            // UpdateProductDto → Product
            // ---------------------------
            // Used when updating an existing product.
            // Id must be mapped so EF Core knows which entity to update.
            CreateMap<UpdateProductDto, Product>();

            // ---------------------------
            // Product → ProductDto
            // ---------------------------
            // Used when returning data to the frontend.
            // Maps all fields including Category reference (if needed).
            CreateMap<Product, ProductDto>()
                .ForMember(dest => dest.CategoryName, opt => opt.MapFrom(src => src.Category.Name));
        }
    }
}