// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartInventory.Data;

#nullable disable

namespace SmartInventory.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260302141901_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SmartInventory.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("240331b3-60d7-45f6-a289-2fa44eb6420f"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("e912b495-4b8e-418e-a8ba-1d7a77861f7a"),
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("SmartInventory.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a7858348-6971-4243-a37e-daab6d6d4334"),
                            CategoryId = new Guid("240331b3-60d7-45f6-a289-2fa44eb6420f"),
                            Name = "Laptop",
                            Price = 0m,
                            Quantity = 5,
                            SKU = ""
                        },
                        new
                        {
                            Id = new Guid("97e1045b-6d5c-4dcb-9c5b-b1d5224082fc"),
                            CategoryId = new Guid("e912b495-4b8e-418e-a8ba-1d7a77861f7a"),
                            Name = "C# Book",
                            Price = 0m,
                            Quantity = 10,
                            SKU = ""
                        });
                });

            modelBuilder.Entity("SmartInventory.Core.Entities.Product", b =>
                {
                    b.HasOne("SmartInventory.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmartInventory.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
