// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartInventory.Data;

#nullable disable

namespace SmartInventory.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260303140722_AddProductDescription")]
    partial class AddProductDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SmartInventory.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b21735e3-2453-41a7-b63e-05c1677282a0"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("a772e954-fc01-4378-b759-435cbd973a37"),
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("SmartInventory.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cabf73d7-5dbc-413b-ad2b-df7d50b09d85"),
                            CategoryId = new Guid("b21735e3-2453-41a7-b63e-05c1677282a0"),
                            Name = "Laptop",
                            Price = 0m,
                            Quantity = 5,
                            SKU = ""
                        },
                        new
                        {
                            Id = new Guid("0151dacf-a48f-4499-b944-861c51e2a415"),
                            CategoryId = new Guid("a772e954-fc01-4378-b759-435cbd973a37"),
                            Name = "C# Book",
                            Price = 0m,
                            Quantity = 10,
                            SKU = ""
                        });
                });

            modelBuilder.Entity("SmartInventory.Core.Entities.Product", b =>
                {
                    b.HasOne("SmartInventory.Core.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SmartInventory.Core.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
